### ISSUE TITLE
Cài đặt trên máy chủ Linux (Ngix)

### ISSUE THREAD

**Issue by vietlhsa** [meesudzu/trac-nghiem-online#10]
Chào tác giả, rất cảm ơn anh đã xây dựng được một trang web kiểm tra trắc nghiệm rất tiện lợi. Tôi có chạy thử trên localhost với xamp thì rất ổn. Tuy nhiên khi triển khai lên máy host NGIX thì bị lỗi này khi chạy install.php để cài đặt, mặc dù đã cấp đủ quyền (777) cho tất cả các thư mục. Tác giả có thể gợi ý nên copy mã nguồn vào thư mục nào trên máy chủ Ngix không? Chân thành cảm ơn.
![image](https://user-images.githubusercontent.com/16033981/69594816-19782400-1030-11ea-992e-2995a24a3fa4.png)
Hình 1. các thư mục trên host.
![image](https://user-images.githubusercontent.com/16033981/69594852-33196b80-1030-11ea-8d8e-9bdf85717d9c.png)
Hình 2. Màn hình thông báo lỗi khi cài đặt.

**Comment by meesudzu** [comment]
Bạn chmod thư mục config và file connect.php nhé. Mà NGINX mình không rõ là có chạy được không nữa, vì mình dùng .htaccess để rwrite url. Tốt nhất vẫn là chạy trên apache nhé.
