### ISSUE TITLE
Lỗi khi cài đặt trên hosting

### ISSUE THREAD

**Issue by habacedu2494** [meesudzu/trac-nghiem-online#11]
Mình mới cài đặt có lẽ không hiểu, mình upload tất cả lên hosting, xong chạy instal thì xuất hiện lỗi như thế này.
Mặc dù đã chmod config.php và connect.php sang 777
Xin ad chỉ giúp ạ!

![image](https://user-images.githubusercontent.com/58985368/71007576-d0d8f580-2119-11ea-9a41-6f3903d253af.png)

**Comment by meesudzu** [comment]
Bạn thử chmod quyển write cả thư mục config nhé. không cần file config.php đâu.

**Comment by habacedu2494** [comment]
> Bạn thử chmod quyển write cả thư mục config nhé. không cần file config.php đâu.

Mình đã làm nhưng vẫn không được, nó vẫn y chang, không biết làm sao nữa, mong bạn giúp mình!

**Comment by meesudzu** [comment]
vậy bạn có thể thực hiện cách thủ công này nhé. Vô /res/files/database.sql để lấy file database. Sau đó import lên mysql. 
Sau đó vô file config/connect.php sửa lại phần kết nối database, quan trọng nhất là INSTALL_MODE => 'false'

**Comment by habacedu2494** [comment]
đã làm được, cám ơn bạn nhiều, bữa mình cài trên linux cũng i chang, giờ cài trên hosting ok rồi.

**Comment by lequyenshpy** [comment]
Mình cài trên localhost lỗi khi Quản lý câu hỏi và quản lý người dùng. Màn hình xoay xoay ko vào dc. Sửa lỗi thế nào ad

**Comment by meesudzu** [comment]
bạn chụp ảnh lỗi hoặc f12console gửi lên mình xem thử nhé.
