### ISSUE TITLE
trac-nghiem-online

### ISSUE THREAD

**Issue by nguyen-dang-hieu9** [meesudzu/trac-nghiem-online#23]
Bạn giúp mình với sao mình đăng nhập được trang admin nhưng vào trang quản-lí-admin nó báo lỗi 404
<img width="1440" alt="Screen Shot 2023-04-11 at 12 12 33" src="https://user-images.githubusercontent.com/98449330/231062323-0b15e3fb-d468-44a7-beb3-0120421b2bfa.png">
<img width="1440" alt="Screen Shot 2023-04-11 at 12 12 37" src="https://user-images.githubusercontent.com/98449330/231062348-b269c174-5c8f-4a74-8593-25fc70da64d7.png">

**Comment by meesudzu** [comment]
Do bạn chưa setting rewrite_url đó.
bạn xem trong phần hướng dẫn có đó.
