### ISSUE TITLE
mình bị lỗi khi nhấn các mục ở phần học sinh thì bị lỗi url 

### ISSUE THREAD

**Issue by quannguyen1231** [meesudzu/trac-nghiem-online#25]
![image](https://github.com/meesudzu/trac-nghiem-online/assets/163869708/e7a94d8b-ceae-49a2-9b72-2a66455398f2)
![image](https://github.com/meesudzu/trac-nghiem-online/assets/163869708/1a077c0f-e1d3-4959-b246-a1a8b270fd4b)

**Comment by meesudzu** [comment]
@quannguyen1231 Do bạn chưa cài mod_rewrite trên xampp cho apache nhé
