### ISSUE TITLE
Hiển thị đúng trường dữ liệu và bổ sung chức năng.

### ISSUE THREAD

**Issue by huynhnv** [meesudzu/trac-nghiem-online#8]
Tôi thấy nên bổ sung chỗ chỉnh sửa học sinh và giáo viên:
- Tại danh sách quản lý học sinh hoặc danh sách quản lý giáo viên khi kích chọn chỉnh sửa thì nên hiển thị đúng trường giới tính và lớp học (đối với danh sách học sinh).
- Cũng tại form chỉnh sửa thông tin, nếu quản trị không gõ mật khẩu thì hệ thống không cần lưu lại giá trị mật khẩu rỗng.
- Tại danh sách quản lý bài kiểm tra, theo tôi nên bổ sung chức năng cho phép chỉnh sửa bài kiểm tra (nếu bài kiểm tra đó chưa có học sinh nào làm bài thi). để quản trị dễ dàng thay đổi các thông tin.
Trân trọng,

**Comment by meesudzu** [comment]
@huynhnv Cảm ơn những đóng góp vô cùng hữu ích của bạn,
Hiện tại mình đang có kế hoạch dựng lại hệ thống này dựa trên các chức năng cũ, dùng 1 số framework về backend và frontend để tối ưu nhất trong việc hiệu năng, bảo mật, bảo trì, nâng cấp cũng như trải nghiệm về phía người dùng. Thay cho hệ thống dựng bằng PHP thuần hiện tại.
Và điều quan trọng nhất của một phần mềm mã nguồn mở là được sự chấp nhận, sử dụng và đóng góp cũng như cùng phát triển của cộng đồng.

**Comment by huynhnv** [comment]
Nếu được như vậy thì rất tốt đó bạn. Sử dụng các nền tảng để phát triển dc thì quá cool.

**Comment by huynhnv** [comment]
Đã có version nào mới chưa bạn ơi?

**Comment by meesudzu** [comment]
Vẫn chưa có thời gian làm tiếp bạn ạ. Delay lâu quá rồi. Cố gắng trong vài tháng nữa vậy.

**Comment by dungav** [comment]
Cám ơn bạn đã chia sẻ sp tuyệt vời này. mình cài đặt đã báo thành công, tuy nhiên khi nhập username đăng nhập là admin, sau đó bấm đăng nhập là quay quay mãi, ko biết nguyên nhân do đâu

**Comment by meesudzu** [comment]
Bạn chụp ảnh f12 console gửi lên hộ mình nhé.

**Comment by dungav** [comment]
![image](https://user-images.githubusercontent.com/33948192/75315392-3e7d6c80-5895-11ea-9ca5-8c3bc40eb3b4.png)

**Comment by dungav** [comment]
cám ơn bạn, xem hộ mình với nhé

**Comment by meesudzu** [comment]
Có vẻ là lỗi bên máy chủ, có thể là không kết nối được cơ sở dữ liệu nên response trả về không đúng.
bạn bật f12 lên, qua tab network, rồi nhấn đăng nhập, chọn vào request vừa gửi, chọn qua tab response hoặc preview để xem nó báo lỗi gì nhé.
như này nè.
![Screenshot-20200226132503-1919x328](https://user-images.githubusercontent.com/17334624/75317786-696abf00-589b-11ea-9978-85a0a008785a.png)

**Comment by dungav** [comment]
![image](https://user-images.githubusercontent.com/33948192/75321059-95d60980-58a2-11ea-9e7b-447fd64142f1.png)

could not find driver bạn ah

**Comment by dungav** [comment]
mình cài apache trên win 10

**Comment by meesudzu** [comment]
Vậy là bạn cài thiếu driver để php kết nối đến mysql rồi.
nếu bạn cài trên máy tính cá nhân thì mình khuyến khích là nên dùng xampp nhé. dễ cài đặt dễ sử dụng.

**Comment by dungav** [comment]
thanks bạn, mình sẽ kiểm tra lại. do vấn đề bảo mật mình ko đc sử dụng xampp hay wamp trên ht
